version: '2.1'
services:
    worker:
        image: puckel/docker-airflow:latest
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./config/worker/airflow.cfg:/usr/local/airflow/airflow.cfg 
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - AWS_ACCESS_KEY_ID=AKIAYCZXYKFO2RZYZCPM
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
        command: worker
